Milestone-1

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("GlobalWeatherRepository.csv")

#Dispaly the first five rows of the data
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,16-05-2024 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,16-05-2024 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,16-05-2024 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,16-05-2024 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,16-05-2024 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55

In [2]:
#Display shape and columns 
#-------------------------
print("Shape:",df.shape)
print("\nColumns:",df.columns.tolist())

Shape: (88468, 41)

Columns: ['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination']

In [3]:
#Get a Dataset info
#------------------
print("\n--- Dataset Info ---")
print(df.info())

#Get a summary stats for nummerical columns
#------------------------------------------
print("\n--- Dataset summery ---")
print(df.describe())

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88468 entries, 0 to 88467
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       88468 non-null  object
 1   location_name                 88468 non-null  object
 2   latitude                      88468 non-null  float64
 3   longitude                     88468 non-null  float64
 4   timezone                      88468 non-null  object
 5   last_updated_epoch            88468 non-null  int64
 6   last_updated                  88468 non-null  object
 7   temperature_celsius           88468 non-null  float64
 8   temperature_fahrenheit        88468 non-null  float64
 9   condition_text                88468 non-null  object
 10  wind_mph                      88468 non-null  float64
 11  wind_kph                      88468 non-null  float64
 12  wind_degree                   88468 non-null  int64
 13  wind_direction                88468 non-null  object
 14  pressure_mb                   88468 non-null  int64
 15  pressure_in                   88468 non-null  float64
 16  precip_mm                     88468 non-null  float64
 17  precip_in                     88468 non-null  float64
 18  humidity                      88468 non-null  int64
 19  cloud                         88468 non-null  int64
 20  feels_like_celsius            88468 non-null  float64
 21  feels_like_fahrenheit         88468 non-null  float64
 22  visibility_km                 88468 non-null  float64
 23  visibility_miles              88468 non-null  int64
 24  uv_index                      88468 non-null  float64
 25  gust_mph                      88468 non-null  float64
 26  gust_kph                      88468 non-null  float64
 27  air_quality_Carbon_Monoxide   88468 non-null  float64
 28  air_quality_Ozone             88468 non-null  float64
 29  air_quality_Nitrogen_dioxide  88468 non-null  float64
 30  air_quality_Sulphur_dioxide   88468 non-null  float64
 31  air_quality_PM2.5             88468 non-null  float64
 32  air_quality_PM10              88468 non-null  float64
 33  air_quality_us-epa-index      88468 non-null  int64
 34  air_quality_gb-defra-index    88468 non-null  int64
 35  sunrise                       88468 non-null  object
 36  sunset                        88468 non-null  object
 37  moonrise                      88468 non-null  object
 38  moonset                       88468 non-null  object
 39  moon_phase                    88468 non-null  object
 40  moon_illumination             88468 non-null  int64
dtypes: float64(21), int64(9), object(11)
memory usage: 27.7+ MB
None

--- Dataset summery ---
           latitude     longitude  last_updated_epoch  temperature_celsius  \
count  88468.000000  88468.000000        8.846800e+04         88468.000000
mean      19.125807     22.172462        1.735550e+09            22.688292
std       24.470764     65.836842        1.137876e+07             9.087760
min      -41.300000   -175.200000        1.715849e+09           -24.900000
25%        3.750000     -6.836100        1.725798e+09            18.000000
50%       17.250000     23.316700        1.735555e+09            25.000000
75%       40.400000     50.580000        1.745399e+09            28.400000
max       64.150000    179.220000        1.755160e+09            49.200000

       temperature_fahrenheit      wind_mph      wind_kph   wind_degree  \
count            88468.000000  88468.000000  88468.000000  88468.000000
mean                72.840627      8.290632     13.345725    170.576988
std                 16.357748      8.131214     13.083663    103.100920
min                -12.800000      2.200000      3.600000      1.000000
25%                 64.400000      4.000000      6.500000     82.000000
50%                 77.000000      6.900000     11.200000    164.000000
75%                 83.100000     11.400000     18.400000    257.000000
max                120.600000   1841.200000   2963.200000    360.000000

        pressure_mb   pressure_in  ...      gust_kph  \
count  88468.000000  88468.000000  ...  88468.000000
mean    1013.968542     29.941857  ...     18.746828
std       11.777453      0.347736  ...     15.079207
min      947.000000     27.960000  ...      3.600000
25%     1010.000000     29.830000  ...     10.700000
50%     1013.000000     29.920000  ...     16.200000
75%     1018.000000     30.050000  ...     24.800000
max     3006.000000     88.770000  ...   2970.400000

       air_quality_Carbon_Monoxide  air_quality_Ozone  \
count                 88468.000000       88468.000000
mean                    517.207265          63.678540
std                     860.050147          33.029201
min                   -9999.000000           0.000000
25%                     234.950000          43.000000
50%                     327.100000          61.000000
75%                     505.050000          81.000000
max                   38879.398000         480.700000

       air_quality_Nitrogen_dioxide  air_quality_Sulphur_dioxide  \
count                  88468.000000                 88468.000000
mean                      15.495710                    11.321146
std                       25.970559                    42.237889
min                        0.000000                 -9999.000000
25%                        1.295000                     0.800000
50%                        4.440000                     2.405000
75%                       17.205000                     9.065000
max                      427.700000                   521.330000

       air_quality_PM2.5  air_quality_PM10  air_quality_us-epa-index  \
count       88468.000000      88468.000000              88468.000000
mean           26.214935         54.267000                  1.760591
std            41.494054        163.103509                  0.987959
min             0.168000      -1848.150000                  1.000000
25%             7.030000         10.500000                  1.000000
50%            14.985000         22.015000                  1.000000
75%            30.340000         46.990000                  2.000000
max          1614.100000       6037.290000                  6.000000

       air_quality_gb-defra-index  moon_illumination
count                88468.000000       88468.000000
mean                     2.770007          50.801035
std                      2.589821          35.105906
min                      1.000000           0.000000
25%                      1.000000          16.000000
50%                      2.000000          52.000000
75%                      3.000000          85.000000
max                     10.000000         100.000000

[8 rows x 30 columns]

In [4]:
#Missing vlaues
print("Missing values per column:\n",df.isnull().sum());

Missing values per column:
 country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [5]:
# Number of countries
print("Unique countries:", df['country'].nunique())

Unique countries: 210

In [6]:
#Unit Conversion / Remove Duplicate Units
#Dropping columns with same measurement in two different units
#Keep only one unit for each measurement (Celsius, km/h, mm, mb, km)
df.drop(columns=[
    'temperature_fahrenheit', 'feels_like_fahrenheit',
    'wind_mph', 'gust_mph',
    'pressure_in', 'precip_in',
    'visibility_miles'
], inplace=True)

print("Remaining columns:", df.columns.tolist())

Remaining columns: ['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'condition_text', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'precip_mm', 'humidity', 'cloud', 'feels_like_celsius', 'visibility_km', 'uv_index', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination']

In [11]:
#Date Handling
#-------------

# Convert last_updated to datetime
df['last_updated'] = pd.to_datetime(df['last_updated'], errors='coerce', dayfirst=False)

# Drop rows where datetime conversion failed
df = df.dropna(subset=['last_updated'])

# Reset index for safety
df = df.reset_index(drop=True)

print("--- Datetime conversion done --- ")
print(df[['last_updated', 'country']].head())

--- Datetime conversion done ---
         last_updated      country
0 2024-05-16 13:15:00  Afghanistan
1 2024-05-16 10:45:00      Albania
2 2024-05-16 09:45:00      Algeria
3 2024-05-16 10:45:00      Andorra
4 2024-05-16 09:45:00       Angola

In [8]:
#Aggregation
#-----------
# Aggregate daily â†’ monthly averages per country
monthly_df = (
    df.groupby([df['last_updated'].dt.to_period('M'), 'country'])
      .mean(numeric_only=True)
      .reset_index()
)

# Rename column
monthly_df.rename(columns={'last_updated': 'year_month'}, inplace=True)
monthly_df['year_month'] = monthly_df['year_month'].astype(str)

print(" --- Monthly Aggregation Done ---")
monthly_df.head()

 --- Monthly Aggregation Done ---

,year_month,country,latitude,longitude,last_updated_epoch,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
0,2024-05,Afghanistan,34.52,69.18,1.716478e+09,20.305882,11.517647,127.941176,1010.000000,0.108824,...,16.141176,1424.094118,77.452941,16.400000,0.588235,7.894118,17.411765,1.000000,1.117647,78.647059
1,2024-05,Albania,41.33,19.82,1.716478e+09,25.647059,13.076471,287.647059,1012.235294,0.295294,...,18.752941,198.223529,87.723529,3.511765,0.447059,10.270588,24.552941,1.352941,1.588235,78.647059
2,2024-05,Algeria,36.76,3.05,1.716478e+09,26.117647,22.617647,182.352941,1013.352941,0.000588,...,28.741176,233.758824,113.935294,10.952941,3.382353,8.682353,18.005882,1.117647,1.117647,78.647059
3,2024-05,Andorra,42.50,1.52,1.716478e+09,12.423529,9.876471,238.235294,1013.000000,0.351765,...,12.617647,151.570588,68.900000,0.741176,0.141176,0.929412,1.211765,1.000000,1.000000,78.647059
4,2024-05,Angola,-8.84,13.23,1.716478e+09,29.088235,19.594118,266.294118,1009.470588,0.000000,...,28.670588,730.600000,105.900000,11.517647,5.976471,45.241176,92.688235,2.529412,4.352941,78.647059

In [9]:
#Yearly Aggregation 
# Extract Year from last_updated
df['year'] = df['last_updated'].dt.year

# Aggregate daily â†’ yearly averages per country
yearly_df = (
    df.groupby(['year', 'country'])
      .mean(numeric_only=True)
      .reset_index()
)

print("--- Yearly Aggregation Done ---")
yearly_df.head()

--- Yearly Aggregation Done ---

,year,country,latitude,longitude,last_updated_epoch,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
0,2024,Afghanistan,34.518703,69.181297,1.725745e+09,22.696943,12.113974,99.257642,1008.096070,0.038603,...,15.079476,774.743013,107.629258,7.655328,7.974389,14.860000,28.745873,1.388646,1.772926,48.672489
1,2024,Albania,41.329017,19.819568,1.725745e+09,25.022271,11.429694,237.855895,1014.899563,0.169651,...,15.961572,257.638646,83.346288,10.230000,4.604236,13.593777,18.724323,1.349345,1.672489,48.606987
2,2024,Algeria,36.761224,3.050237,1.725762e+09,25.154386,15.312719,174.412281,1017.035088,0.025351,...,20.516228,307.305263,88.343860,30.107917,12.673136,18.584364,35.214364,1.574561,2.122807,48.394737
3,2024,Andorra,42.500000,1.518703,1.725745e+09,14.105677,9.516594,211.502183,1017.965066,0.147860,...,11.872052,177.131659,64.942358,0.616790,0.162074,3.729760,7.693100,1.030568,1.048035,48.606987
4,2024,Angola,-8.839332,13.231729,1.725745e+09,26.335808,13.153712,260.231441,1012.550218,0.030044,...,19.632314,690.936900,117.070306,9.025524,8.001550,47.178341,82.926769,2.484716,4.301310,48.606987

In [10]:
#Save Aggregated Datasets

# Save both aggregated datasets
monthly_df.to_csv("Monthly_GlobalWeather.csv", index=False)
yearly_df.to_csv("Yearly_GlobalWeather.csv", index=False)

print(" Saved as Monthly_GlobalWeather.csv and Yearly_GlobalWeather.csv")

 Saved as Monthly_GlobalWeather.csv and Yearly_GlobalWeather.csv

Milestone-1 completed